- hosts: control_main
  name: Static gitlab secrets.
  become: true
  tasks:

    - name: Generate an OpenSSH rsa openid_connect_signing_key
      community.crypto.openssh_keypair:
        path: /tmp/id_ssh_rsa
        size: 2048

    - name: Slurp openid_connect_signing_key
      ansible.builtin.slurp:
        src: /tmp/id_ssh_rsa
      register: slurp_openid_connect_signing_key

    - name: Password example
      ansible.builtin.set_fact:
        root:
          kas_secrets:
            kas_shared_secret: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            kas_private_api: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            kas_websocket_token: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
          rails_secrets:
            secret_key_base: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            otp_key_base: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            db_key_base: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            encrypted_settings_key_base: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            openid_connect_signing_key: "{{ slurp_openid_connect_signing_key.content | b64decode | replace('\n','\n    ') | b64encode  }}"
            active_record_encryption_primary_key: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            active_record_encryption_deterministic_key: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            active_record_encryption_key_derivation_salt: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            suggested_reviewers: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
          gitlab_secrets:
            password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
            workhorse: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
          gitaly_secrets:
            token: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=8) }}"
            token_shell: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=8) }}"
          registry_secrets:
            httpSecret: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=64) }}"
            notification: "[{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}]"
            host: "gitlab-registry.gitlab.svc"
            username: "registry"
            password: "!!!token-from-gitlab!!!"
          pages_secrets:
            secret: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=32) }}"
          runner_secrets:
            runner_registration_token: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=64) }}"

    - name: gitlab-secrets.yaml
      ansible.builtin.copy:
        content: "{{ root | from_yaml }}"
        dest: /tmp/gitlab-secrets.yaml
        force: yes

    - name: Gitlab secrets
      ansible.builtin.set_fact:
        gitlab_secrets: "{{ lookup('ansible.builtin.file', '/run/secrets/gitlab-secrets.yaml')   }}"

    - debug: msg={{ gitlab_secrets }}

    - debug: msg={{ gitlab_secrets.gitaly_secrets.token }}