{
 "title": "Test custom metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "Loki", "label": "Loki", "query": "loki" },
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{cluster=~\"$cluster\",namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "loki-alerts-rules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HighPercentageError",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(rate({pod=~\".+\"} |~ \"(?i)error\" [5m])) by (pod) / sum(rate({pod=~\".+\"}[5m])) by (pod) > 0.05",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "HighPercentageWarn",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(rate({pod=~\".+\"} |~ \"(?i)warn\" [5m])) by (pod) / sum(rate({pod=~\".+\"}[5m])) by (pod) > 0.05",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "HighPercentageDEBUG",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(rate({pod=~\".+\"} |~ \"(?i)debug\" [5m])) by (pod) / sum(rate({pod=~\".+\"}[5m])) by (pod) > 0.05",
       "legendFormat": "{{label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Test custom and external metrics.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "HighCPUUsage (disable monitoring)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "100 - (avg by(node) (irate(node_cpu_seconds_total{mode=\"idle\", node=~\"control01|workflow01\"}[5m])) * 100) > 30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HighCPUUsage (bool)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 - (avg by(node) (irate(node_cpu_seconds_total{mode=\"idle\", node=~\"control01|workflow01\"}[5m])) * 100)) <= bool 80",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "shell_connection_count(custom_metric)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ssh_active_sessions{namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "shell_connection_count(external_metric)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ssh_active_sessions{namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  }
 ]
}