apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    url: https://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
    access: proxy
    isDefault: true
    secureJsonData:
      tlsCACert: '/run/secrets/kubernetes.io/serviceaccount/ca.crt'
  - name: Loki
    type: loki
    access: proxy
    url: https://loki-read.monitoring.svc:3100
    isDefault: true
    jsonData:
      timeout: 60
      maxLines: 1000
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: https://alertmanager-operated.monitoring.svc:9093  # Обычно Alertmanager работает на 9093
    isDefault: true  # Делаем Alertmanager источником по умолчанию для алертов
    jsonData:
      implementation: prometheus  # Указываем, что это Prometheus Alertmanager
      handleGrafanaManagedAlerts: true  # Разрешает принимать алерты из Grafana
      handleAlerts: true  # Включает обработку алертов
      timeout: 30