apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    url: https://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
    access: proxy
    isDefault: true
    secureJsonData:
      tlsCACert: '/run/secrets/kubernetes.io/serviceaccount/ca.crt'
  - name: Loki
    type: loki
    access: proxy
    url: http://loki-read.monitoring.svc:3100
    jsonData:
      timeout: 60
      maxLines: 1000